### PR TITLE
Blog app - creating a data model

### PR DESCRIPTION
**Pull request by keza681**
## Hello 👋 , Reviewers!
In this PR, I have implemented the required tasks listed below :

### TASKS 
- Create a new app. Give it a meaningful name.
- Initialize your project with Git.
Important: do NOT use rails generate scaffold command. The point of this project is to show you how to set up controllers by yourself.
- Make sure that your project has Postgres database set up.
- Take a look at the wireframes below. Make sure that your app handles the URLs used in the wireframes:
- For each URL you should create:
A route.
- An action in the correct controller.
- A view file.
- View files should include only placeholders written in plain HTML,

### CODE REVIEW

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Linda, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
Git flow is followed. :heavy_check_mark:
## To Improve 🙏
- [ ] There are no migrations for data tables. Kindly see the project requirements [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/creating_data_model_project_v1_1.md) and add all the migrations for the data model.

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by keza681** [comment]
thanks @SajjadAhmad14, I went through the codes and created migrations after db creation.

**Review by codepantha — CHANGES_REQUESTED** [review]
# STATUS: REQUIRED CHANGES ♻️ 

## Hi @keza681 👋, 

You've done well implementing some of the requested changes by the previous reviewer 👋, but there are still some which aren't addressed yet.

### Highlights ⭐ 
✔️ Descriptive PR
✔️ Correct Gitflow
✔️ Linter checks are passing

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Just like the previous reviewer suggested, please create migrations for the `users`, `posts`, `comments`, and `likes` table. Kindly see the project requirements [here](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/creating_data_model_project_v1_1.md) and add all the migrations for the data model.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by keza681** [comment]
thanks @SajjadAhmad14 , @codepantha for your feedback. Now All migrations are running

**Review by RolandM99 — APPROVED** [review]
<h1>Status: Approve 🥇 ✔</h1>
Hi @keza681, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
